language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
dist: xenial
sudo: true
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
matrix:
  exclude:
    # Python/Django combinations that aren't officially supported
    - { python: 2.7, env: DJANGO=2.0 }
    - { python: 2.7, env: DJANGO=2.1 }
    - { python: 2.7, env: DJANGO=2.2 }
    - { python: 2.7, env: DJANGO=3.1 }
  include:
    - { python: 3.8, env: TOXENV=flake8 }
    - { python: 3.8, env: TOXENV=docs }

install:
  - pip install tox-travis
script:
  - tox
